 import './Globals.css'
  export const metadata = {
  title: "Rudresh - Résumé",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body>
        {children}
      </body>
    </html>
  );
}
